### ISSUE TITLE
Design a FAQ page with a dropdown

### ISSUE THREAD

**Issue by Samadeen** [zuri-training/Team-44_Chunk-file#22]

**Comment by danielbriggz** [comment]
FAQ page light mode design
https://www.figma.com/file/hpTCxerYLCRoqq4HBKz2pk/PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY?node-id=1867%3A6524

**Comment by danielbriggz** [comment]
Prototype for the FAQ page (light mode)

https://www.figma.com/proto/hpTCxerYLCRoqq4HBKz2pk/PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY?node-id=1867%3A6524&scaling=scale-down&page-id=630%3A699&starting-point-node-id=1027%3A1539&show-proto-sidebar=1

**Comment by Samadeen** [comment]
Oil plenty for your head
