### ISSUE TITLE
Design a Draft screen

### ISSUE THREAD

**Issue by Samadeen** [zuri-training/Team-44_Chunk-file#27]

**Comment by De-mi-de** [comment]
We are currently working on it

**Comment by Phannyx** [comment]
This has already been resolved. We designed the draft page (hi-fi, mid-fi and lo-fi) for both new and existing users

Hi-fi
https://www.figma.com/file/mURSGFsm0Hx7tTKxTL6Kbw/(control-version)-PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY-Team-version?node-id=887%3A785

Our figma file
https://www.figma.com/file/mURSGFsm0Hx7tTKxTL6Kbw/(control-version)-PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY-Team-version?node-id=887%3A785
