### ISSUE TITLE
Modify About us Page

### ISSUE THREAD

**Issue by Jonathan-Tech-Sudo** [zuri-training/Team-44_Chunk-file#35]

**Comment by Phannyx** [comment]
Please has this been done? So it can be ready for prototyping

**Comment by Chimelly** [comment]
Welldone guys

**Comment by danielbriggz** [comment]
I and @vharsce are done modifying the About us page and it's ready for prototyping

https://www.figma.com/file/hpTCxerYLCRoqq4HBKz2pk/PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY?node-id=2408%3A19786
