### ISSUE TITLE
Prototype Sign Up and Sign In page

### ISSUE THREAD

**Issue by Phannyx** [zuri-training/Team-44_Chunk-file#42]

**Comment by Quin-Didi** [comment]
Don't forget to include the filled states for the sign-up and sign-in pages

**Comment by Joshuua1** [comment]
Working on it

**Comment by Phannyx** [comment]
@Quin-Didi how do you mean please? I thought its the developers work to  make these fields active

**Comment by Phannyx** [comment]
Thanks. This has been resolved

**Comment by Phannyx** [comment]
we prototyped for both light mode and dark mode
https://www.figma.com/file/mURSGFsm0Hx7tTKxTL6Kbw/(control-version)-PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY-Team-version?node-id=887%3A785
