### ISSUE TITLE
About Us Page Redesign

### ISSUE THREAD

**Issue by Jonathan-Tech-Sudo** [zuri-training/Team-44_Chunk-file#54]

**Comment by Phannyx** [comment]
i have seen it, lovely work .

**Comment by danielbriggz** [comment]
Light mode - https://www.figma.com/file/mURSGFsm0Hx7tTKxTL6Kbw/(control-version)-PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY-Team-version?node-id=2472%3A37861

Dark mode - https://www.figma.com/file/mURSGFsm0Hx7tTKxTL6Kbw/(control-version)-PROJECT_TEAM_44-CHUNK_FILES-PROJECT-LIBRARY-Team-version?node-id=2472%3A28893
