### ISSUE TITLE
Slides Arrangements

### ISSUE THREAD

**Issue by Samadeen** [zuri-training/Team-44_Chunk-file#78]

**Comment by Phannyx** [comment]
This has been resolved. Thanks.
https://www.figma.com/file/Xc1fmDGzbFr8qvTkdj3FdX/project-chunk-file-Team-44--Presentation-Slide?node-id=0%3A1s

**Comment by Phannyx** [comment]
In the link, you will see the content i created and the slides i designed for the presentation
