### ISSUE TITLE
your frontend work is now live

### ISSUE THREAD

**Issue by rhedwan** [zuri-training/Team-44_Chunk-file#93]
https://chunkeet.zurifordummies.com/

the CSS is not loading I'm, I would check if it is from my end

**Comment by iyaji1883** [comment]
@Samadeen  can you jump in on this?.

**Comment by iyaji1883** [comment]
@rhedwan  thanks and please let us know how it goes

**Comment by Samadeen** [comment]
Okay.. Thanks
Everything works fine after running on local machine.. It might be from their end

**Comment by iyaji1883** [comment]
Ok

**Comment by yomabd** [comment]
We are getting closer. But everything was working perfectly locally
